<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Yukako Ito | <?php echo $pageTitle ?></title>
	<link rel="stylesheet" href="css/main.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<link  href="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.css" rel="stylesheet">
	<script src="http://cdnjs.cloudflare.com/ajax/libs/fotorama/4.6.4/fotorama.js"></script>
</head>

<body>
<div class="container">

	<header>
		<h1><a href="index.php">Yukako Ito | <?php echo $pageTitle ?></a></h1>
		<?php include "inc/nav.inc" ?>
	</header>